# commented because we areusing config server 
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true 
#  instance:
#    prefer-ip-address: true
    
server: 
  port: 8084

spring:
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:8086  
