eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    
server:
  port: 8086

spring:
  cloud: 
    config:
      server:
        git:
          uri: https://github.com/prktech96/microservice-config
          clone-on-start: true
  application:
    name: CONFIG-SERVER
