server:
  port: 7777

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    prefer-ip-address: true

spring:
  main:
    web-application-type: reactive
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-provider/**,/transaction/**
        - id: SHOPPING-SERVICE
          uri: lb://SHOPPING-SERVICE
          predicates:
            - Path=/amazon-payment/**
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://dev-64766424.okta.com/oauth2/default
#          jwk-set-uri: https://dev-64766424.okta.com/oauth2/default/v1/keys
#  config:
#    import: configserver:http://localhost:8086

#okta configuration for api gateway

#okta:
#  oauth2:
#    issuer: https://dev-64766424-admin.okta.com/oauth2/default
#    audience: api://default
#    client-id: 0oal0e30gas7k4XNi5d7
#    client-secret: pDOCfkIfiUoopNjM2QVkjVCibfxQOHcFP4t8t3-hGOB_K4U0ifR0pYELY49mJJxC
#    scopes: openid, profile, email, offline_access


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true